services:
  - type: web
    name: focusai
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn -w 1 app:app --bind 0.0.0.0:$PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

        